apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "palantir.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "palantir.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  ADMIN_EMAIL: {{ .Values.env.adminEmail | quote }}
  DATA_FILE_PATH: {{ .Values.env.dataFilePath | quote }}
  {{- if .Values.env.oidc.issuer }}
  OIDC_ISSUER: {{ .Values.env.oidc.issuer | quote }}
  {{- end }}
  {{- if .Values.env.oidc.clientId }}
  OIDC_CLIENT_ID: {{ .Values.env.oidc.clientId | quote }}
  {{- end }}
  {{- if .Values.env.oidc.redirectUri }}
  OIDC_REDIRECT_URI: {{ .Values.env.oidc.redirectUri | quote }}
  {{- end }}
  {{- if .Values.env.oidc.adminGroup }}
  OIDC_ADMIN_GROUP: {{ .Values.env.oidc.adminGroup | quote }}
  {{- end }}
  {{- if and .Values.env.oidc.issuer .Values.env.oidc.scopes }}
  OIDC_SCOPES: {{ .Values.env.oidc.scopes | quote }}
  {{- end }}
